---
title: "cell with spot analysis"
format: html
editor_options: 
  chunk_output_type: console
---

## load packages
```{r}
# rstudioapi::getActiveDocumentContext()$path |>
#   dirname() |>
#   setwd()

project_dir <- "D:/Postdoc_Data/2024-02-04_MYC_swapping"
setwd(project_dir)

# load packages
library(tidyverse)
library(cowplot)
library(lemon)
library(ggridges)
```

## read cellprofiler db
```{r}
# load function
source("D:/Script/R_functions/read_sqlite.R")

classify_table <- "cell_class"
# classify_table <- NULL

# read db
raw <- read_sqlite("cp_result.db", classify_table)
# raw <- map("cp_result.db", read_sqlite) %>% 
#   bind_rows(.id="Metadata_source")

glimpse(raw$image)
glimpse(raw$objects)
```

## define magnification
```{r}
magification <- "60x"
image_width <- unique(raw$image$Image_Width)

# unit: um
objective_view <- c("100x" = 133, "60x" = 221, "20x" = 600)
length_per_pixel <- objective_view[magification] * (1/image_width)
print(str_glue("per pixel length: {round(length_per_pixel, 3)} uM"))
```

## metadata plate info
```{r}
# load function
source("D:/Script/R_functions/read_plate_info.R")

# get plate info
plate_info_f <- "plate_info.xlsx"

if(file.exists(plate_info_f)) {
  plate_info <- plate_info_f %>%
    map_dfr(read_plate_info_1, add_directory=F) %>%
    # separate_wider_delim(Metadata_group, delim = "+",
    #                      names = c("Metadata_vectorFP", "Metadata_addFP"),
    #                      too_few = "align_start",
    #                      cols_remove = F) %>% 
    # separate_wider_delim(Metadata_vectorFP, delim = "-",
    #                      names = c("Metadata_vector", NA),
    #                      too_few = "align_start",
    #                      cols_remove = F) %>% 
    # mutate(across(c(Metadata_group, Metadata_vectorFP, 
    #                 Metadata_vector, Metadata_addFP), 
    #               ~ replace_na(.x, ""))) %>% 
    mutate(Metadata_vector = factor(Metadata_vector,
                                   levels=unique(Metadata_vector)),
           Metadata_conc = factor(Metadata_conc,
                                   levels=unique(Metadata_conc)))
  
  plate_info
  
} else {
  plate_info <- NULL
}

```


## tidy image
```{r}
image <- raw$image %>% 
  select(!c(starts_with("Image_Count_"),
            matches("Image_Intensity_Percentile_[25]_.*"))) %>% 
  rename_with(\(x) str_replace(x, "Intensity_Percentile_1", "bg"))
# glimpse(image)

if(exists("plate_info")) {
  image <- image %>% 
    left_join(plate_info, 
              by=join_by(Metadata_well))
}
# add metadta
image$Metadata_position %>% unique()
# image <- image %>% 
#   mutate(Metadata_prefix=str_replace_all(
#     Metadata_prefix, ".*-per-", "")) %>% 
#   mutate(Metadata_group=case_when(
#     Metadata_position %in% 1:10 ~ "Vector",
#     Metadata_position %in% 11:20 ~ "YAP-WT",
#     Metadata_position %in% 21:30 ~ "YAP-detlaTAD",
#     Metadata_position %in% 31:40 ~ "YAPMAML2"
#   ), .after = Metadata_position) 
```

## tidy cell
```{r}
# glimpse(raw$objects$cell)
cell <- raw$objects$cell %>% 
  select(!any_of(c("cell_Parent_mask_cp_masks_cell",
                 "cell_Parent_FilterObjects",
                 "cell_Children_cell_wo_spot_Count"))) %>% 
  right_join(image, ., 
             by=join_by(ImageNumber)) %>% 
  # scale pixel to actual length
  mutate(across(matches(
    "(Diameter)|(AxisLength)|(Radius)|(Perimeter)$"),
    \(x) x * length_per_pixel)) %>% 
  mutate(across(matches(
    "(Area)$"),
    \(x) x * length_per_pixel * length_per_pixel))
# glimpse(cell)

# cell model classification
cell <- cell %>% 
  right_join(raw$objects$cell_class, .,
            by=join_by(ImageNumber, cell_Number_Object_Number)) %>% 
  rename(Metadata_cell_class=class)

# # cell wo spot
# cell_wo_spot <- raw$objects$cell_wo_spot %>% 
#   select(ImageNumber,
#          ends_with("Parent_cell"),
#          ends_with("AreaShape_Area"),
#          contains("_Intensity_")
#          )
# # glimpse(cell_wo_spot)
# 
# # cell + cell wo spot
# cell <- cell %>% 
#   left_join(cell_wo_spot,
#             by=join_by(
#               ImageNumber,
#               cell_Number_Object_Number==cell_wo_spot_Parent_cell))
# glimpse(cell)
# 
# # remove unneeded variables
# rm(cell_wo_spot)
```

<!-- ## tidy spot -->
<!-- ```{r} -->
<!-- # glimpse(raw$objects$spot) -->
<!-- spot <- raw$objects$spot %>%  -->
<!--   filter(spot_Parent_cell != 0) %>%  -->
<!--   filter((spot_AreaShape_MajorAxisLength /  -->
<!--             spot_AreaShape_MinorAxisLength) < 3, -->
<!--          spot_AreaShape_Area > 6) %>%  -->
<!--   select(!c(spot_Children_cell_wo_spot_Count)) %>%  -->
<!--   select(!c(contains("RadialDistribution_FracAtD"), -->
<!--             contains("RadialDistribution_RadialCV"))) %>%  -->
<!--   select(!setdiff(contains("AreaShape"),  -->
<!--                   contains("EquivalentDiameter"))) %>% -->
<!--   # spot_Parent_cell==0 means related to background -->
<!--   right_join(cell, .,  -->
<!--              by=join_by( -->
<!--                ImageNumber, -->
<!--                cell_Number_Object_Number==spot_Parent_cell)) -->
<!-- # glimpse(spot) -->

<!-- # spot rbg -->
<!-- spot_rbg <- raw$objects$spot_rbg %>%  -->
<!--   select(ImageNumber, -->
<!--          contains("Parent_spot_expand_l"), -->
<!--          contains("Intensity")) -->
<!-- # glimpse(spot_rbg) -->

<!-- # spot + spot rbg -->
<!-- spot <- spot %>%  -->
<!--   left_join(spot_rbg, -->
<!--             by=join_by( -->
<!--               ImageNumber, -->
<!--               spot_Number_Object_Number==spot_rbg_Parent_spot_expand_l)) -->

<!-- # add spot type -->
<!-- spot <- spot %>%  -->
<!--   left_join(spot_type,  -->
<!--             by = join_by( -->
<!--               ImageNumber, -->
<!--               spot_Number_Object_Number==spot_Number_Object_Number )) -->

<!-- glimpse(spot) -->

<!-- # remove unneeded variables -->
<!-- rm(spot_rbg) -->
<!-- ``` -->

## subtract background
```{r}
# get all channel names
channels <- colnames(image) %>% 
  str_subset("Image_bg") %>% 
  str_replace_all("Image_bg_", "")

# process one channel each time
for(ch in channels) {
  cell <- cell %>% 
  rowwise() %>% 
  mutate(across(
    c(matches(str_glue(".*Intensity_{ch}$"))), 
    \(x) max(0, (x - !!as.name(str_glue("Image_bg_{ch}"))))) ) %>% 
    ungroup()
  
  # spot <- spot %>% 
  #   rowwise() %>% 
  #   mutate(across(
  #     c(matches(str_glue(".*Intensity_{ch}$"))), 
  #     \(x) max(0, (x - !!as.name(str_glue("Image_bg_{ch}"))))) ) %>% 
  #   ungroup()
}

# glimpse(cell)
# glimpse(spot)

# cell <- cell %>% 
#   filter(!is.na(Metadata_group))
# spot <- spot %>% 
#   filter(!is.na(Metadata_group))
```

## SAVE
```{r}
writexl::write_xlsx(
  list(cell=cell),
  str_glue("{Sys.Date()}_data_cell.xlsx"))
```


## visulization

## object size
```{r}
objects <- c("cell")
group_var <- "Metadata_vector"
fill_var <- "Metadata_vector"
fact_var <- "Metadata_conc" # NA mean no additional facet beside channel

for(obj in objects) {
  if(is.na(fact_var)) {
    eval(parse(text=obj)) %>% 
      ggplot(aes(!!as.name(str_glue(
        "{obj}_AreaShape_EquivalentDiameter")), 
                 !!as.name(group_var),
                 fill = !!as.name(fill_var))) +
      geom_density_ridges(color = "grey80", linewidth=0.1,
                          scale = 1.5, show.legend = F) +
      labs(x=str_glue("Diameter of {obj} [uM]"), y="") +
      # coord_cartesian(xlim = c(0, 200), ylim = c(0, 2000)) +
      theme_bw(8) +
      theme(strip.background = element_rect(fill=NA), 
            strip.text = element_text(size=6),
            panel.grid = element_blank(),
            legend.position = "top")
    
    ggsave2(str_glue("{Sys.Date()}_{obj}_diameter.pdf"),
            width=1, 
            height=length(unique(eval(parse(text=obj))[[group_var]])) * 0.4)
    
  } else {
    eval(parse(text=obj)) %>% 
      ggplot(aes(!!as.name(str_glue(
        "{obj}_AreaShape_EquivalentDiameter")), 
                 !!as.name(group_var),
                 fill = !!as.name(fill_var))) +
      geom_density_ridges(color = "grey80", linewidth=0.1,
                          scale = 1.5, show.legend = F) +
      ggh4x::facet_grid2(cols=vars(!!as.name(fact_var)),
                         # rows=vars(!!as.name(fact_var)),
                         scales = "fixed",
                         space = "fixed",
                         axes  = "y",
                         remove_labels = "y") +
      labs(x=str_glue("Diameter of {obj} [uM]"), y="") +
      # coord_cartesian(xlim = c(0, 200), ylim = c(0, 2000)) +
      theme_bw(8) +
      theme(strip.background = element_rect(fill=NA), 
            strip.text = element_text(size=6),
            panel.grid = element_blank(),
            legend.position = "top")
    
    ggsave2(str_glue("{Sys.Date()}_{obj}_diameter.pdf"),
            width=length(unique(eval(parse(text=obj))[[fact_var]])) * 1, 
            height=length(unique(eval(parse(text=obj))[[group_var]])) * 0.4)
  }
  
} 
  
```
  
## object intenstiy
```{r}
objects <- c("cell")
group_var <- "Metadata_vector"
fill_var <- "Metadata_vector"
fact_var <- "Metadata_conc" # NA mean no additional facet beside channel

for(obj in objects) {
  if(is.na(fact_var)) {
    eval(parse(text=obj)) %>% 
      pivot_longer(
        any_of(as.character(str_glue(
          "{obj}_Intensity_MeanIntensity_{channels}"))),
        names_to = "channel", 
        names_prefix = str_glue("{obj}_Intensity_MeanIntensity_"),
        values_to = "Intensity"
      ) %>% # glimpse()
      ggplot(aes(Intensity, !!as.name(group_var),
                 fill = !!as.name(fill_var))) +
      geom_density_ridges(color = "grey80", linewidth=0.1,
                          scale = 1.5, show.legend = F) +
      scale_x_continuous(trans = scales::log2_trans()) +
      ggh4x::facet_grid2(cols=vars(channel),
                         # rows=vars(!!as.name(fact_var)),
                         scales = "free_x",
                         space = "fixed",
                         axes  = "y",
                         remove_labels = "y") +
      labs(x="Intensity (log2)",y="") +
      # coord_cartesian(xlim = c(0, 1000)) +
      theme_bw(8) +
      theme(strip.background = element_rect(fill=NA), 
            strip.text = element_text(size=6),
            panel.grid = element_blank(),
            legend.position = "top")
    ggsave2(str_glue("{Sys.Date()}_{obj}_intensity_log2.pdf"),
            width=1.5*length(channels), 
            height=length(unique(eval(parse(text=obj))[[group_var]])) * 0.25)
    
  } else {
    eval(parse(text=obj)) %>% 
      pivot_longer(
        any_of(as.character(str_glue(
          "{obj}_Intensity_MeanIntensity_{channels}"))),
        names_to = "channel", 
        names_prefix = str_glue("{obj}_Intensity_MeanIntensity_"),
        values_to = "Intensity"
      ) %>% # glimpse()
      ggplot(aes(Intensity, !!as.name(group_var),
                 fill = !!as.name(fill_var))) +
      geom_density_ridges(color = "grey80", linewidth=0.1,
                          scale = 1.5, show.legend = F) +
      scale_x_continuous(trans = scales::log2_trans()) +
      ggh4x::facet_grid2(cols=vars(channel),
                         rows=vars(!!as.name(fact_var)),
                         scales = "free_x",
                         space = "fixed",
                         axes  = "y",
                         remove_labels = "y") +
      labs(x="Intensity (log2)",y="") +
      # coord_cartesian(xlim = c(0, 1000)) +
      theme_bw(8) +
      theme(strip.background = element_rect(fill=NA), 
            strip.text = element_text(size=6),
            panel.grid = element_blank(),
            legend.position = "top")
    ggsave2(str_glue("{Sys.Date()}_{obj}_intensity_log2.pdf"),
            width=1.5*length(channels), 
            height=length(unique(eval(parse(text=obj))[[group_var]])) * 0.2 *
              length(unique(eval(parse(text=obj))[[fact_var]])))
  }
  
}
```

## cell classification class
```{r}
cell %>% 
  mutate(Metadata_cell_class=factor(Metadata_cell_class,
                                    rev(c("none", "spot", "aggregate")))) %>%
  ggplot(aes(Metadata_vector, 
             fill=Metadata_cell_class)) +
  geom_bar(width = 0.75) +
  # geom_col(position = "stack") +
  scale_fill_manual(values = c("#005a32", "#41ab5d", "#c7e9c0")) +
  labs(x="") +
  theme_bw() +
  theme(legend.position = "top",
        legend.title = element_blank())
ggsave2(str_glue("{Sys.Date()}_cell_classification.pdf"),
        width=4, 
        height=3)
```


## cell granularity
```{r}
plate_var <- "Metadata_prefix"
axis_var <- "cell_Intensity_MeanIntensity_ch1"
# color_var <- "Metadata_vector"
group_var <- "Metadata_vector"
# fill_var <- "Metadata_vector"
fact_var <- "Metadata_conc" # NA mean no additional facet beside channel

cell %>% 
  filter(between(cell_AreaShape_EquivalentDiameter, 10, 20)) %>% 
  filter(between(cell_Intensity_MeanIntensity_ch1, 200, 20000)) %>% 
  pivot_longer(
    matches("Granularity_.*"),
    # any_of(as.character(str_glue("cellRegion_Intensity_MeanIntensity_{channels}"))),
    names_to = c("granularity_order", "channel"), 
    names_pattern = "cell_Granularity_(.+)_(.+)$",
    # names_prefix = "cellRegion_Intensity_MeanIntensity_",
    values_to = "granularity_value") %>% 
  filter(granularity_order %in% 2:4) %>% 
  mutate(granularity_order=str_c("Granularity_", granularity_order)) %>% 
  ggplot(aes(!!as.name(axis_var), granularity_value,
             color=!!as.name(group_var),
             fill=!!as.name(group_var))) +
  geom_point(color = "grey8 0", size=0.2, alpha=0.25) +
  geom_smooth(linewidth=1, method = "loess", span=0.7) + # 
  ggh4x::facet_grid2(rows = vars(!!as.name(fact_var)),
                     # cols = vars(granularity_order, channel),
                     cols = vars(!!as.name(group_var)),
                     # scales = "free",
                     independent = "none"
                     ) +
  scale_x_continuous(trans = scales::log2_trans()) +
  labs(x="log2(Intensity)", y="Granularity") +
  # labs(x="Concentration [uM]", y="Texture Granularity of Cell") +
  # coord_cartesian(xlim = c(0, 0.8), ylim = c(0, 8)) +
  # scale_x_continuous(breaks = seq(0, 1.2, 0.2)) +
  # scale_y_continuous(breaks = seq(0, 10, 2)) +
  theme_bw() +
  theme(strip.background = element_rect(fill=NA), 
        strip.text = element_text(size=4),
        # panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none")
ggsave2(str_glue("{Sys.Date()}_cell_intensity_vs_granularity.pdf"),
        width=2*ncol(select(cell, contains("Granularity_"))), 
        height=1*length(unique(cell[[fact_var]])), 
        limitsize=F)
```


<!-- ## spot ratio -->
<!-- ```{r} -->
<!-- data_plot <- channels %>%  -->
<!--   set_names(., nm=.) %>%  -->
<!--   map(\(ch)  -->
<!--       spot %>%  -->
<!--         mutate("spot_ratio_cell_{ch}" :=  -->
<!--                  !!as.name(str_glue("spot_Intensity_MeanIntensity_{ch}")) /  -->
<!--                  !!as.name(str_glue("cell_Intensity_MeanIntensity_{ch}"))  -->
<!--                ) %>%  -->
<!--         pivot_longer( -->
<!--           c(!!as.name(str_glue("spot_ratio_cell_{ch}"))), -->
<!--           names_to = "type", values_to = "Ratio") %>%  -->
<!--         separate_wider_regex(type,  -->
<!--                              c(type="spot_ratio_.*", "_", channel="ch[0-9]") ) -->
<!--       ) %>%  -->
<!--   bind_rows() # pull(channel) %>% unique() -->

<!-- data_plot %>%  -->
<!--   ggplot(aes(log2(Ratio),  -->
<!--              Metadata_group,  -->
<!--              fill=type, color=type)) + -->
<!--   # geom_point(alpha=0.25, size=0.5) + -->
<!--   # geom_smooth(show.legend = T) + -->
<!--   # ggbeeswarm::geom_beeswarm() + -->
<!--   # geom_boxplot() + -->
<!--   geom_density_ridges(color = "grey80", linewidth=0.1, -->
<!--                       scale = 1.5, show.legend = F) + -->
<!--   facet_rep_wrap(~ Metadata_prefix + channel,  -->
<!--                  ncol = length(channels), -->
<!--                  scales = "fixed",  -->
<!--                  repeat.tick.labels = T) + -->
<!--   # labs(x="log2(Intensity)", y="Spark count") + -->
<!--   # coord_cartesian(ylim = c(0, 50)) + -->
<!--   theme_bw(8) + -->
<!--   theme(strip.background = element_rect(fill=NA),  -->
<!--         strip.text = element_text(size=6), -->
<!--         panel.grid = element_blank(), -->
<!--         legend.position = "top") -->
<!-- ggsave2(str_glue("{Sys.Date()}_spot_ratio.pdf"), -->
<!--         width = 6,  -->
<!--         height = 5) -->


<!-- ``` -->


<!-- ## spot intensity vs cell intensity -->
<!-- ```{r} -->
<!-- spot %>%  -->
<!--   # filter(class=="positive") %>%  -->
<!--   # filter(spot_Intensity_MeanIntensity_ch2_Probabilities > 0.2) %>%  -->
<!--   # filter(spot_AreaShape_EquivalentDiameter > 2) %>% -->
<!--   # filter(!(Metadata_group != "Vector" &  -->
<!--   #          cell_Intensity_MeanIntensity_ch1 < 800)) %>%  -->
<!--   # filter(between(cell_Intensity_MeanIntensity_ch2, 800, 3000)) %>%  -->
<!--   ggplot(aes(cell_Intensity_MeanIntensity_ch2, -->
<!--              spot_Intensity_MeanIntensity_ch2)) + -->
<!--   geom_point(aes(fill=Metadata_group, -->
<!--                  size=spot_AreaShape_EquivalentDiameter),  -->
<!--              shape = 21, stroke = 0.1, -->
<!--              color = "transparent", -->
<!--              alpha = 0.5, show.legend = T) + -->
<!--   guides(size = guide_legend(override.aes = list(alpha=1))) + -->
<!--   scale_x_continuous(trans = scales::log2_trans()) + -->
<!--   scale_y_continuous(trans = scales::log2_trans()) + -->
<!--   scale_size_continuous(range=c(0.3, 3)) + -->
<!--   ggh4x::facet_grid2(cols=vars(Metadata_group),  -->
<!--                      rows=vars(Metadata_prefix), -->
<!--                      remove_labels="all") + -->
<!--   # coord_cartesian(xlim = c(0, 12000), ylim = c(0, 12000)) + -->
<!--   labs(x="Cell Intensity (log)", y="Spot intensity (log)") + -->
<!--   theme_bw() + -->
<!--   theme(strip.background = element_rect(fill=NA),  -->
<!--         strip.text = element_text(size=6), -->
<!--         legend.title = element_blank(), -->
<!--         legend.text=element_text(size=4), -->
<!--         legend.key.size = unit(3, "pt"), -->
<!--         # panel.grid = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         legend.position = "top") -->

<!-- ggsave2(str_glue("{Sys.Date()}_spot_intensity_vs_cell_intensity.pdf"), -->
<!--         ggrastr::rasterise(last_plot(), dpi=600), -->
<!--         width = 6,  -->
<!--         height = 6) -->


<!-- spot %>%  -->
<!--   filter(class=="positive") %>% -->
<!--   # filter(spot_Intensity_MeanIntensity_ch2_Probabilities > 0.2) %>% -->
<!--   filter(spot_AreaShape_EquivalentDiameter > 1) %>% -->
<!--   # filter(!(Metadata_group != "Vector" & -->
<!--   #          cell_Intensity_MeanIntensity_ch1 < 800)) %>% -->
<!--   # filter(between(cell_Intensity_MeanIntensity_ch2, 800, 3000)) %>%  -->
<!--   ggplot(aes(cell_Intensity_MeanIntensity_ch2, -->
<!--              spot_Intensity_MeanIntensity_ch2)) + -->
<!--   geom_point(aes(fill=Metadata_group, -->
<!--                  size=spot_AreaShape_EquivalentDiameter),  -->
<!--              shape = 21, stroke = 0.1, -->
<!--              color = "transparent", -->
<!--              alpha=0.5, show.legend = F) + -->
<!--   scale_x_continuous(trans = scales::log2_trans()) + -->
<!--   scale_y_continuous(trans = scales::log2_trans()) + -->
<!--   scale_size_continuous(range=c(0.3, 3)) + -->
<!--   ggh4x::facet_grid2(cols=vars(Metadata_group),  -->
<!--                      rows=vars(Metadata_prefix), -->
<!--                      remove_labels="all") + -->
<!--   # coord_cartesian(xlim = c(0, 12000), ylim = c(0, 12000)) + -->
<!--   labs(x="Cell Intensity (log)", y="Spot intensity (log)") + -->
<!--   coord_fixed() + -->
<!--   theme_bw() + -->
<!--   theme(strip.background = element_rect(fill=NA),  -->
<!--         strip.text = element_text(size=6), -->
<!--         # panel.grid = element_blank(), -->
<!--         panel.grid.major = element_blank(), -->
<!--         legend.position = "top") -->

<!-- ggsave2(str_glue("{Sys.Date()}_spot_intensity_vs_cell_intensity_filtered.pdf"), -->
<!--         ggrastr::rasterise(last_plot(), dpi=600), -->
<!--         width = 6,  -->
<!--         height = 6) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- group_var <- "Metadata_group" -->
<!-- fill_var <- "Metadata_group" -->

<!-- library(ggridges) -->
<!-- # intensity -->
<!-- spot %>%  -->
<!--   pivot_longer( -->
<!--     any_of(as.character(str_glue("spot_Intensity_MeanIntensity_{channels}"))), -->
<!--     names_to = "channel",  -->
<!--     names_prefix = "spot_Intensity_MeanIntensity_", -->
<!--     values_to = "Intensity" -->
<!--   ) %>% #glimpse() -->
<!--   ggplot(aes(Intensity, -->
<!--              !!as.name(group_var), -->
<!--              fill = !!as.name(fill_var))) + -->
<!--   geom_density_ridges(color = "grey80", linewidth=0.1, -->
<!--                       scale = 1.5, show.legend = F) + -->
<!--   scale_x_continuous(trans = scales::log2_trans()) + -->
<!--   facet_rep_wrap(~ Metadata_prefix + channel, -->
<!--                  nrow = 1, -->
<!--                  scales = "fixed", -->
<!--                  repeat.tick.labels = T) + -->
<!--   labs(x="Intensity (log2)",y="") + -->
<!--   # coord_cartesian(xlim = c(0, 1000)) + -->
<!--   theme_bw(8) + -->
<!--   theme(strip.background = element_rect(fill=NA),  -->
<!--         strip.text = element_text(size=6), -->
<!--         panel.grid = element_blank(), -->
<!--         legend.position = "top") -->
<!-- ggsave2(str_glue("{Sys.Date()}_cell_intensity_log2.pdf"), -->
<!--         width=4*length(channels),  -->
<!--         height=length(unique(cell[[group_var]]))/4) -->


<!-- spot %>%  -->
<!--   # filter(class=="positive") %>%  -->
<!--   filter(spot_Intensity_MeanIntensity_ch2_Probabilities > 0.5) %>%  -->
<!--   ggplot(aes(cell_Intensity_MeanIntensity_ch1, -->
<!--              spot_Intensity_MeanIntensity_ch2)) + -->
<!--   geom_point(aes(color=Metadata_group), alpha=0.5, show.legend = F) + -->
<!--   ggh4x::facet_grid2(cols=vars(Metadata_group), rows=vars(Metadata_prefix), -->
<!--                      remove_labels="none") + -->
<!--   theme_bw() -->

<!-- spot %>%  -->
<!--   # filter(class=="positive") %>%  -->
<!--   filter(spot_Intensity_MeanIntensity_ch2_Probabilities > 0.5) %>%  -->
<!--   ggplot(aes(cell_Intensity_MeanIntensity_ch2, -->
<!--              spot_Intensity_MeanIntensity_ch2)) + -->
<!--   geom_point(aes(color=Metadata_group), alpha=0.5, show.legend = F) + -->
<!--   ggh4x::facet_grid2(cols=vars(Metadata_group),  -->
<!--                      remove_labels="none") + -->
<!--   theme_bw() -->

<!-- spot %>%  -->
<!--   # filter(class=="positive") %>%  -->
<!--   # filter(spot_Intensity_MeanIntensity_ch2_Probabilities > 0.2) %>%  -->
<!--   filter(spot_AreaShape_EquivalentDiameter > 2) %>% -->
<!--   # filter(!(Metadata_group != "Vector" &  -->
<!--   #          cell_Intensity_MeanIntensity_ch1 < 800)) %>%  -->
<!--   # filter(between(cell_Intensity_MeanIntensity_ch2, 800, 3000)) %>%  -->
<!--   ggplot(aes(cell_Intensity_MeanIntensity_ch2, -->
<!--              spot_Intensity_MeanIntensity_ch2)) + -->
<!--   geom_point(aes(color=Metadata_group, -->
<!--                  size=spot_AreaShape_EquivalentDiameter),  -->
<!--              alpha=0.75, show.legend = F) + -->
<!--   scale_size_continuous(range=c(0.2, 2)) + -->
<!--   ggh4x::facet_grid2(cols=vars(Metadata_group), rows=vars(Metadata_prefix), -->
<!--                      remove_labels="none") + -->
<!--   theme_bw() -->

<!-- spot %>%  -->
<!--   # filter(class=="positive") %>%  -->
<!--   filter(spot_Intensity_MeanIntensity_ch2_Probabilities > 0.5) %>%  -->
<!--   ggplot(aes(cell_Intensity_MeanIntensity_ch2, -->
<!--              spot_Intensity_MeanIntensity_ch2)) + -->
<!--   geom_point(aes(color=Metadata_group, -->
<!--                  size=spot_AreaShape_EquivalentDiameter),  -->
<!--              alpha=0.25, show.legend = F) + -->
<!--   scale_size_continuous(range=c(0.2, 4)) + -->
<!--   ggh4x::facet_grid2(cols=vars(Metadata_group),  -->
<!--                      remove_labels="none") + -->
<!--   theme_bw() -->


<!-- spot %>%  -->
<!--   # filter(class=="positive") %>%  -->
<!--   filter(spot_Intensity_MeanIntensity_ch2_Probabilities > 0.5) %>%  -->
<!--   ggplot(aes(cell_Intensity_MeanIntensity_ch2, -->
<!--              spot_Intensity_MeanIntensity_ch2_Probabilities)) + -->
<!--   geom_point(aes(color=Metadata_group), alpha=0.5, show.legend = F) + -->
<!--   ggh4x::facet_grid2(cols=vars(Metadata_group),  -->
<!--                      remove_labels="none") + -->
<!--   theme_bw() -->

<!-- spot %>%  -->
<!--   # filter(class=="positive") %>%  -->
<!--   # filter(spot_Intensity_MeanIntensity_ch2_Probabilities > 0.5) %>%  -->
<!--   ggplot(aes(cell_Intensity_MeanIntensity_ch2_Probabilities, -->
<!--              spot_Intensity_MeanIntensity_ch2_Probabilities)) + -->
<!--   geom_point(aes(color=Metadata_group), alpha=0.5, show.legend = F) + -->
<!--   ggh4x::facet_grid2(cols=vars(Metadata_group),  -->
<!--                      remove_labels="none") + -->
<!--   theme_bw() -->


<!-- spot %>%  -->
<!--   # filter(class=="positive") %>%  -->
<!--   filter(spot_Intensity_MeanIntensity_ch2_Probabilities > 0.5) %>%  -->
<!--   reframe(n=n(), .by=c(Metadata_group, ImageNumber, -->
<!--                        cell_Number_Object_Number)) %>%  -->
<!--   mutate(n=ifelse(n>4, 4, n)) %>%  -->
<!--   reframe(n2 = n(), .by=c(Metadata_group, n)) %>%  -->
<!--   mutate(across(c(n), as.factor)) %>%  -->
<!--   arrange(Metadata_group, n) %>%  -->
<!--   ggplot(aes(Metadata_group, n2, group=Metadata_group, fill=n)) + -->
<!--   geom_col(position = position_fill()) + -->
<!--   # geom_bar(position = position_fill()) + -->
<!--   # geom_point(aes(color=Metadata_group), alpha=0.5, show.legend = F) + -->
<!--   # geom_boxplot() + -->
<!--   # geom_violin() +,  -->
<!--   # ggh4x::facet_grid2(cols=vars(Metadata_group),  -->
<!--   #                    remove_labels="none") + -->
<!--   # coord_cartesian(ylim=c(0, 3)) + -->
<!--   theme_bw() -->


<!-- ``` -->


<!-- ## cell spot intensity in one plot -->
<!-- ```{r} -->
<!-- data_plot <- channels %>%  -->
<!--   set_names(., nm=.) %>%  -->
<!--   map(\(ch)  -->
<!--       spot %>%  -->
<!--         pivot_longer( -->
<!--           c(!!as.name(str_glue("cell_Intensity_MeanIntensity_{ch}")), -->
<!--             # !!as.name(str_glue("cell_wo_spot_Intensity_MeanIntensity_{ch}")), -->
<!--             # !!as.name(str_glue("spot_rbg_Intensity_MeanIntensity_{ch}")),  -->
<!--             !!as.name(str_glue("spot_Intensity_MeanIntensity_{ch}")) ), -->
<!--           names_to = "type", values_to = "Intensity") %>%  -->
<!--         separate_wider_delim(type, "_Intensity_MeanIntensity_", -->
<!--                              names = c("type", "channel")) ) %>%  -->
<!--   bind_rows() # pull(channel) %>% unique() -->

<!-- if(is.na(fact_var)) { -->
<!--   p <- data_plot %>%  -->
<!--     ggplot(aes(spot_AreaShape_EquivalentDiameter,  -->
<!--                Intensity, -->
<!--                fill=type, color=type)) + -->
<!--     geom_point(alpha=0.25, size=0.5) + -->
<!--     geom_smooth(show.legend = T) + -->
<!--     ggh4x::facet_grid2(rows = vars(!!as.name(group_var)), -->
<!--                        cols = vars(channel), -->
<!--                        axes = "all", -->
<!--                        # scales = "free_y", -->
<!--                        # remove_labels = "all", -->
<!--                        independent = "none") + -->
<!--     # facet_rep_grid(rows = vars(!!as.name(group_var)), -->
<!--     #                cols = vars(channel), -->
<!--     #                scales = "free_x", -->
<!--     #                repeat.tick.labels = T) + -->
<!--     scale_y_continuous(trans = scales::log2_trans()) + -->
<!--     labs(x="Spot Diameter [uM]", y="Intensity (log2)") + -->
<!--     # coord_cartesian(ylim = c(0, 150)) + -->
<!--     theme_bw(8) + -->
<!--     theme(strip.background = element_rect(fill=NA),  -->
<!--           strip.text = element_text(size=6), -->
<!--           panel.grid = element_blank(), -->
<!--           legend.position = "top") -->
<!--   p -->
<!--   ggsave2(str_glue("{Sys.Date()}_spot_diameter_vs_intensity_log2.pdf"), -->
<!--           ggrastr::rasterize(p, dpi=600), -->
<!--           width=2*length(channels),  -->
<!--           height=length(unique(cell[[group_var]]))*2) -->

<!-- } else { -->
<!--   data_plot %>%  -->
<!--     ggplot(aes(Metadata_group,  -->
<!--                spot_AreaShape_EquivalentDiameter, -->
<!--                fill=type, color=type)) + -->
<!--     geom_point(alpha=0.25, size=0.5) + -->
<!--     # geom_smooth(show.legend = T) + -->
<!--     facet_rep_wrap(~ Metadata_prefix + channel,  -->
<!--                    scales = "fixed",  -->
<!--                    repeat.tick.labels = T) + -->
<!--     # labs(x="log2(Intensity)", y="Spark count") + -->
<!--     # coord_cartesian(xlim = c(0, 40), ylim = c(0, 10000)) + -->
<!--     theme_bw(8) + -->
<!--     theme(strip.background = element_rect(fill=NA),  -->
<!--           strip.text = element_text(size=6), -->
<!--           panel.grid = element_blank(), -->
<!--           legend.position = "top") -->
<!--   ggsave2(str_glue("{Sys.Date()}_spot_diameter_vs_intensity.pdf"), -->
<!--           width=6, height=5) -->
<!-- } -->



<!-- data_plot %>%  -->
<!--   ggplot(aes(Metadata_group, Intensity, log2(Intensity), -->
<!--              fill=type, color=type)) + -->
<!--   geom_point(alpha=0.25, size=0.5) + -->
<!--   geom_smooth(show.legend = T) + -->
<!--   facet_rep_wrap(~ Metadata_group + channel,  -->
<!--                  scales = "fixed",  -->
<!--                  repeat.tick.labels = T) + -->
<!--   # labs(x="log2(Intensity)", y="Spark count") + -->
<!--   # coord_cartesian(ylim = c(0, 150)) + -->
<!--   theme_bw(8) + -->
<!--   theme(strip.background = element_rect(fill=NA),  -->
<!--         strip.text = element_text(size=6), -->
<!--         panel.grid = element_blank(), -->
<!--         legend.position = "top") -->
<!-- ggsave2(str_glue("{Sys.Date()}_spot_diameter_vs_intensity_log2.pdf"), -->
<!--         width=6, height=5) -->
<!-- ``` -->


<!-- ## spot radial -->
<!-- ```{r} -->
<!-- if(F) { -->
<!--   data_plot <- spot %>%  -->
<!--     filter(spot_AreaShape_EquivalentDiameter > 5, -->
<!--            spot_RadialDistribution_MeanFrac_ch1_5of5 > 0.5 -->
<!--     ) %>% -->
<!--     pivot_longer( -->
<!--       contains("spot_RadialDistribution_MeanFrac"), -->
<!--       names_to = c("channel", "radial_order"),  -->
<!--       names_sep = "_", -->
<!--       names_prefix = "spot_RadialDistribution_MeanFrac_", -->
<!--       values_to = "MeanFrac") %>%  -->
<!--     mutate(radial_order=radial_order %>%  -->
<!--              str_replace_all("of5","") %>%  -->
<!--              as.integer()) -->
<!--   # filter(spot_Number_Object_Number %in% 5) %>%  -->
<!--   # glimpse() -->

<!--   data_plot %>%  -->
<!--     ggplot(aes(radial_order, MeanFrac)) + -->
<!--     # geom_point(alpha=0.25, size=0.5) + -->
<!--     geom_path(aes(color=log2(spot_AreaShape_EquivalentDiameter), -->
<!--                   group=str_c(ImageNumber, spot_Number_Object_Number))) + -->
<!--     scale_color_viridis_c() + -->
<!--     # geom_smooth(show.legend = T) + -->
<!--     facet_rep_wrap(~ Metadata_group + channel,  -->
<!--                    scales = "fixed",  -->
<!--                    repeat.tick.labels = T) + -->
<!--     # labs(x="log2(Intensity)", y="Spark count") + -->
<!--     # coord_cartesian(ylim = c(0, 150)) + -->
<!--     theme_bw(8) + -->
<!--     theme(strip.background = element_rect(fill=NA),  -->
<!--           strip.text = element_text(size=6), -->
<!--           panel.grid = element_blank(), -->
<!--           legend.position = "top") -->
<!--   ggsave2(str_glue("{Sys.Date()}_spot_radial_vs_meanfrac.pdf"), -->
<!--           width=6, height=5) -->
<!-- } -->
<!-- ``` -->


