---
title: "qPCR Analysis"
author: "Hao He"
format: html
number-sections: true
execute-cache: true
editor_options: 
  chunk_output_type: console
---

# setup
```{r}
rstudioapi::getActiveDocumentContext()$path |>
  dirname() |>
  setwd()
# setwd("/media/hao/Data/2024-05-01_RTKs_active_mutations")

library(tidyverse)
library(cowplot)
library(writexl)

# load function
c("read_plate_info.R", "ggplot_helper.R") %>% 
  file.path("/home/hao/Documents/GitHub/myScript/R_functions", .) %>% 
  walk(source)

# transform A01, B13 to A1, B13 style
transform_well_style <- function(well) {
  tmp <- str_extract(well, "(?<row>[A-Za-z])(?<column>[0-9]+)", group=1:2)
  # print(tmp)
  str_c(tmp[1], as.integer(tmp[2]))
}
```

# read plate info
```{r}
plate_info_f <- "plate_info.xlsx"

plate_info <- plate_info_f %>%
  map_dfr(read_plate_info_1, colname_prefix="") %>%
  print()
```


# --------------------------
# read Cq
```{r}
cq_file <- list.files("export", "Quantification Cq Results.csv", full.names=T)
# cq_file <-"qPCR_20250422_hh -  Quantification Cq Results.csv"

cq <- read_csv(cq_file) %>% 
  dplyr::select(well=Well, cq=Cq) %>% 
  mutate(well=map_chr(well, transform_well_style)) %>% 
  print()

# merge with metadata
cq <- plate_info %>% 
  # mutate(Metadata_conc=as.numeric(Metadata_conc)) %>% 
  left_join(cq) %>%
  # dplyr::select(!well) %>% 
  filter(!is.na(cq), !is.na(gene), !is.na(sample)) %>% 
  print()
```

# pseudo well
```{r}
if(T) {
  add_observation <- function(df, min_n=3, value_col="cq") {

    if (is.null(df) || !is.data.frame(df) || ncol(df) == 0) {
      return(tibble(!!value_col := numeric(0)))  # return empty tibble with correct column
    }
    
    if(nrow(df) < min_n) {
      print("add pseudo well value")
      df <- tibble(!!value_col := rnorm(min_n - nrow(df),
                                        mean=mean(df[[value_col]], na.rm=T),
                                        sd=sd(df[[value_col]], na.rm=T))) %>% 
        bind_rows(df, .)
    }
    return(df)
  }
  
  # set.seed(42)
  cq <- cq %>% 
    group_by(gene, sample) %>%
    nest() %>%
    mutate(data=map(data, \(x) add_observation(x))) %>% 
    unnest(data) %>%
    ungroup() %>% 
    print()
}
```


# delta Cq
```{r}
ref_gene <- "ACTB"

delta_cq_ref <- cq %>% 
  filter(gene == ref_gene) %>% 
  reframe(cq_ref_gene=mean(cq, na.rm=T), .by=sample) %>% 
  print()
delta_cq <- cq %>% 
  left_join(delta_cq_ref) %>% 
  mutate(delta_cq=(cq - cq_ref_gene)) %>% 
  print()
```

# delta delta Cq
```{r}
ref_sample <- "Parental"

delta_delta_cq_ref <- delta_cq %>% 
  filter(sample == ref_sample) %>% 
  reframe(cq_ref_sample=mean(delta_cq, na.rm=T), .by=gene) %>% 
  print()
delta_delta_cq <- delta_cq %>% 
  left_join(delta_delta_cq_ref) %>% 
  mutate(dedlta_delta_cq=(delta_cq - cq_ref_sample)) %>% 
  mutate(fc=2^(-dedlta_delta_cq)) %>% 
  arrange(sample, gene) %>% 
  print()
```


# plot & save
```{r}
delta_delta_cq %>% 
  filter(gene != ref_gene) %>%
  mutate(sample=factor(sample, c("Parental","Day3","Day7","Resist"))) %>% 
  ggplot(aes(sample, fc)) +
  stat_summary(geom="errorbar", fun.data=mean_se, 
               width=0.4, color="grey20", position=position_dodge(0.85)) + # "#4575b4"
  stat_summary(geom="bar", fun=mean, 
               width=0.8, fill="#4575b4", position=position_dodge(0.85)) +
  facet_wrap(vars(gene), scales="free", axis.labels="all", ncol=2) +
  labs(x="", y="Relative mRNA level") +
  # guides(fill="none") + 
  # coord_cartesian(ylim=c(0.75, NA)) +
  # labs(y="ERK-KTR Activity") +
  my_theme()

ggsave(str_glue("{Sys.Date()}_delta_delta_cq.pdf"), width=3, height=4)
writexl::write_xlsx(
  delta_delta_cq, str_glue("{Sys.Date()}_delta_delta_cq.xlsx"))
```

```{r}
delta_delta_cq %>% 
  filter(gene != ref_gene) %>%
  filter(gene == "FGFR1") %>% 
  mutate(sample=factor(sample, c("Parental","Day3","Day7","Resist"))) %>% 
  ggplot(aes(sample, fc)) +
  stat_summary(geom="errorbar", fun.data=mean_se, 
               width=0.4, color="grey20", position=position_dodge(0.85)) + # "#4575b4"
  stat_summary(geom="bar", fun=mean, 
               width=0.8, fill="#4575b4", position=position_dodge(0.85)) +
  facet_wrap(vars(gene), scales="free", axis.labels="all", ncol=2) +
  labs(x="", y="Relative mRNA level") +
  ggbreak::scale_y_break(c(2, 265)) +
  # guides(fill="none") + 
  # coord_cartesian(ylim=c(0.75, NA)) +
  # labs(y="ERK-KTR Activity") +
  my_theme()
ggsave(str_glue("{Sys.Date()}_delta_delta_cq_FGFR1.pdf"), width=2, height=2)
```



# --------------------------
# melting curve
```{r}
curve_file <- list.files("export", "Melt Curve Derivative Results_SYBR.csv", full.names=T)
# curve_file <- "qPCR_20250422_hh -  Melt Curve Derivative Results.csv"

curve <- read_csv(curve_file) %>% 
  dplyr::select(!1) %>% 
  pivot_longer(!Temperature, names_to="well", values_to="value") %>% 
  left_join(plate_info, .) %>% 
  print()

curve %>% 
  ggplot(aes(Temperature, value, color=well)) +
  geom_line(show.legend=F) +
  facet_grid(rows=vars(gene), 
             cols=vars(sample),
             axes="all", axis.labels="margins") +
  labs(y="RFU Derivative") +
  my_theme(angle=0)

ggsave(str_glue("{Sys.Date()}_delta_delta_cq_mc.pdf"), width=6, height=6)
```

```{r}

```

