---
title: "cellprofiler analysis"
format: html
editor_options: 
  chunk_output_type: console
---

# prepare data

```{r}
rstudioapi::getActiveDocumentContext()$path |>
  dirname() |>
  setwd()

# options("repos" = c(CRAN="https://mirrors.ustc.edu.cn/CRAN/")) 
# options(BioC_mirror="https://mirrors.ustc.edu.cn/bioc/")
options("repos" = c(CRAN="https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
options(BioC_mirror="https://mirrors.tuna.tsinghua.edu.cn/bioconductor")

# load packages
library(rio)
options(rio.import.class='tbl')
library(patchwork)
library(RSQLite)
library(RColorBrewer)
library(tidyverse)
library(magrittr)

# load helper function
c("helper.R") %>% 
  file.path("C:/Users/haohe/GitHub/myScript/R", .) %>%
  walk(source)

# set wd
r"(E:\TP53\2026-08-12_barcoding_assay\2026-07-30_mix_12cmpd)" %>% 
  norm_path() %>% 
  setwd()
getwd()
```


## read inference

```{r}
infer_db_files <- list.files(
  '.', pattern='infer.*db$', recursive=T, full.names=T) %>% 
  set_names(., nm=basename(dirname(.))) %>%
  str_subset('2026-07-30') %>%
  str_subset('infer_p53.db', negate = F) %>%
  print()
if(length(infer_db_files) > 0) {
  infer <- infer_db_files %>% 
    # x <- infer_db_files[2]
    map(\(x) read_sqlite(x, skip_tables=c('reduction_pca_variance','sqlite_sequence')) %>% 
          map(\(y) dplyr::select(y, !any_of('features'))) %>% 
          # combine tables by shared uid key
          base::Reduce(\(m, n) list_cbind_efficient(m, n, by=c("uid")), .) %>% 
          as_tibble() %>% 
          dplyr::select(!any_of(c('filename', 'mask_filename', 'uid'))) %>% 
          dplyr::relocate(starts_with('umap_'), starts_with('pc_'), .after=last_col()) %>% 
          dplyr::rename_with(\(z) str_c(z, str_replace(basename(x),'.db', ''), sep='_'), 
                             c(matches('^(umap_|pc_|pred_)'))) #%>% glimpse
    ) %>% 
    list_rbind(names_to='directory') %>% 
    glimpse()
}

barcode_db_files <- list.files(
  '.', pattern='infer.*db$', recursive=T, full.names=T) %>% 
  set_names(., nm=basename(dirname(.))) %>%
  str_subset('2026-07-30') %>%
  str_subset('infer_barcode.db', negate = F) %>%
  print()
if(length(barcode_db_files) > 0) {
  barcode <- barcode_db_files %>% 
    # x <- barcode_db_files[2]
    map(\(x) read_sqlite(x, skip_tables=c('reduction_pca_variance','sqlite_sequence')) %>% 
          map(\(y) dplyr::select(y, !any_of('features'))) %>% 
          # combine tables by shared uid key
          base::Reduce(\(m, n) list_cbind_efficient(m, n, by=c("uid")), .) %>% 
          as_tibble() %>% 
          dplyr::select(!any_of(c('filename', 'mask_filename', 'uid'))) %>% 
          dplyr::relocate(starts_with('umap_'), starts_with('pc_'), .after=last_col()) %>% 
          dplyr::rename_with(\(z) str_c(z, str_replace(basename(x),'.db', ''), sep='_'), 
                             c(matches('^(umap_|pc_|pred_)'))) #%>% glimpse
    ) %>% 
    list_rbind(names_to='directory') %>% 
    glimpse()
}
```

## read microprofiler

```{r}
# microprofiler
db_files <- list.files(
  '.', pattern='result.*db$', recursive=T, full.names=T) %>% 
  set_names(., nm=basename(dirname(.))) %>%
  str_subset('2026-07-30') %>%
  print()
if(length(db_files) > 0) {
  raw_list <- map(db_files, read_sqlite)
  # merge all same table into one list item
  raw <- names(raw_list[[1]]) %>% 
    set_names(names(raw_list[[1]])) %>% 
    map(\(x) map(raw_list, \(y) y[[x]]) %>% 
          list_rbind(names_to='directory')
        )
  rm(raw_list)
  # glimpse(raw)
  
  # assign each object
  for(table_name in intersect(names(raw), c('cell','nuclei')))
    assign(table_name, raw[[table_name]] %>% glimpse())
}
```


## merge all db

```{r}
if(length(infer_db_files) > 0) {
  join_cols <- intersect(names(cell), names(infer)) %>% print()
  
  cell[join_cols] <- lapply(cell[join_cols], as.character)
  infer[join_cols] <- lapply(infer[join_cols], as.character)
  if(exists('barcode'))
    barcode[join_cols] <- lapply(barcode[join_cols], as.character)
  
  cell <- left_join(cell, infer) %>% 
    {if(exists('barcode')) right_join(barcode, .) else . } %>% 
    {if('directory' %in% colnames(.)) {
      mutate(., directory=str_replace_all(directory, '__.*', ''))
    } else . } %>% 
    {if(any(str_detect(colnames(.), '^umap_'))) {
      dplyr::filter(., !if_any(matches('^umap_'), is.na))
    } else . } %>% 
    glimpse()
}
```

## set channel

```{r}
if(F) {
  # manually define channel names
  channel_names <- c("BFP"="ch1", "GFP"="ch2", "IFP"="ch3")
  
  for(idx in seq_along(channel_names)) {
    # rename each table
    print(paste0('rename channel: ', table, 
                 'with: ', channel_names[idx]))
    cell <- cell %>% 
      rename_with(\(x) str_replace(
        x, channel_names[idx], names(channel_names)[idx]))
  }
}
```

# merge plate info

```{r}
plate_info_files <- list.files(
  ".", ".*xlsx", recursive=F, full.names=T) %>% 
  set_names(., nm=basename(.) %>% str_replace_all(".xlsx", "")) %>% 
  print()
if(length(plate_info_files) > 0) {
  plate_info <- plate_info_files %>%
    map(read_metadata) %>%
    {
      if(length(plate_info_files) > 1) 
        list_rbind(., names_to='directory') else list_rbind(.)
    } %>% 
    # rename(Metadata_vector=value) %>% 
    # separate_wider_delim(value, delim=regex("[+ ]"),
    #                      names=c("Metadata_vector", "Metadata_type", "Metadata_adaptor"),
    #                      too_few="align_start",
    #                      cols_remove=T) %>%
    # mutate(Metadata_vector=factor(Metadata_vector, c("Gal4DBD","APP","NOTCH1"))) %>%
    # mutate(Metadata_conc=as.numeric(Metadata_conc))
    print()
  
  # modify directory to match each other
  setdiff(plate_info$directory, cell$directory)
  cell <- cell %>% 
    separate_wider_regex(directory, c(
      directory=".*_", temperature="22|37", "_cmpd", "(?:__Measurement \\d)?"), 
      cols_remove = T, too_few = "align_start") %>% 
    print()
  
  # merge with plate_info
  cell <- cell %>% 
    right_join(plate_info, .) %>% 
    glimpse()
}
```

# *modify object

```{r}
cell_tidy <- cell %>% 
  # regular filter
  dplyr::filter(shape_edge_pixel_ratio < 0.5) %>%
  dplyr::filter(intensity_mean_ch2 > 250, intensity_mean_ch2 < 2000) %>%
  dplyr::filter(shape_eccentricity > 0.45, shape_eccentricity < 0.95) %>%
  # mutate(timepoint=ifelse(is.na(timepoint), "37-2h",
  #                         ifelse(timepoint=="1", "22-4h", "22-8h"))) %>%
  # optical barcode
  {if(exists('barcode')) 
    dplyr::filter(., pred_prob_infer_barcode > 0.75) %>% 
      dplyr::select(!any_of(c("ground_truth", "pred_prob_infer_barcode"))) %>% 
      dplyr::rename(barcode = pred_class_infer_barcode) else .} %>% 
  # inference: convert prob to [0, 1] for single type prob
  {if(exists("infer"))
    mutate(., target_pred_prob = case_when(
      pred_class_infer_p53 == "pos" ~ pred_prob_infer_p53,
      pred_class_infer_p53 == "neg" ~ 1 - pred_prob_infer_p53,
      TRUE ~ NA_real_), .before=pred_prob_infer_p53) %>%
      dplyr::select(!c(pred_class_infer_p53, pred_prob_infer_p53)) else .} %>% 
  # factorize cmpd, conc
  {if("cmpd" %in% colnames(.)) {
    mutate(., cmpd=factor(cmpd, unique(c("DMSO", cmpd))))
  } else . } %>% 
  {if("conc" %in% colnames(.)) {
    mutate(., conc=round(as.numeric(conc), 4) %>% 
             factor(., levels=sort(unique(.))))
  } else . } %>% 
  glimpse()


if(F) {
  cell$intensity_mean_ch2 %>% quantile(seq(0, 1, 0.05))
  cell$shape_eccentricity %>% quantile(seq(0, 1, 0.05))
  count(cell_tidy, directory)
  count(cell_tidy, well) %>% print(n=50)
  count(cell_tidy, field)
  print(cell_tidy)
  glimpse(cell_tidy)
}
```

# *summarize to field

```{r}
measure_pattern <- "shape|intensity|granularity|glcm|radial|pred_prob"

meta_colnames <- colnames(cell_tidy) %>% 
  str_subset(measure_pattern, negate=T) %>% 
  str_subset("object_id|label|well", negate = T) %>% 
  str_subset("pc_|umap_", negate=T) %>% 
  print()

# per_field
cell_tidy_per_field <- cell_tidy %>% 
  reframe(across(matches(measure_pattern), \(x) mean(x, trim=0, na.rm=T)),
          target_pos_ratio = mean(target_pred_prob > 0.5, na.rm = T), # custom stats
          cell_count_per_field = n(),  # cell count
          .by=any_of(c(meta_colnames, "field"))) %>%   # group by
  glimpse()
# per_well
cell_tidy_per_well <- cell_tidy_per_field %>% 
  reframe(across(!field, list(mean=\(x) mean(x, trim=0, na.rm=T), se=se)),
          .by=any_of(setdiff(meta_colnames, "field"))) %>% 
  relocate(ends_with("_se"), .after = last_col()) %>% 
  glimpse()

# glimpse(cell_tidy_per_field)
```

# save data

```{r}
list(
  # cell_tidy=cell_tidy,
  cell_tidy_per_field=cell_tidy_per_field,
  cell_tidy_per_well=cell_tidy_per_well
) %>% 
  export(str_glue("{Sys.Date()}_data.xlsx"))
```


# plot

## *prepare data

```{r}
# plot_obj <- "cell_tidy"
plot_obj <- "cell_tidy_per_field"

plot_items <- colnames(get(plot_obj)) %>% 
  setdiff(meta_colnames) %>% 
  str_subset("well|label|object_id|is_boundary|ground_truth", negate=T) %>% 
  str_subset("shape_edge_pixel_ratio|shape_area|shape_extent|shape_solidity|shape_perimeter", negate=T) %>% 
  str_subset("shape_feret_diameter_max|shape_major_axis_length|shape_minor_axis_length", negate=T) %>% 
  str_subset("intensity_median|intensity_std|intensity_sum", negate=T) %>% 
  str_subset("statistic|pvalue", negate=T) %>% 
  str_subset("pc_|umap_", negate=T) %>% 
  str_subset("glcm_", negate=T) %>%
  str_subset("spot", negate=T) %>%
  unique() %>% 
  print()
# plot_items <-c("cell_count", "cell_area", "shape_extent")

pdata <- get(plot_obj) %>% 
  # {if("well" %in% colnames(.)) {
  #   mutate(., well=factor(
  #     well, str_sort(unique(well), numeric=T))) %>% 
  #     mutate(row=str_extract(well, "(\\w)\\d+", group=1),
  #            col=str_extract(well, "\\w(\\d+)", group=1) %>% 
  #              {factor(., unique(sort(as.numeric(.))))}, 
  #            .before=1)
  # } else .} %>% 
  # # norm by day0 ---------------------------
  # mutate(across(all_of(plot_items),
  #               \(x) round(x / mean(x[date == "06-28"], na.rm=T), 3)),
  #        .keep="used",
  #        .by=c(cell, cmpd, density, conc)) %>%
  # ## norm by DMSO ---------------------------
  # # mutate(conc=conc,
  # #        across(all_of(plot_items), 
  # #               \(x) round(x / mean(x[cmpd == "DMSO"], na.rm=T), 3)),
  # #        .keep="used",
  # #        .by=c(cell, date, density)) %>% 
  # ## norm by lowest conc ---------------------------
  # mutate(cmpd=cmpd,
  #        across(all_of(plot_items),
  #               \(x) round(x / mean(x[conc == min(.data[["conc"]])]), 3)),
  #        .keep="used",
  #        .by=c(cell, date, density)) %>%
  
  # filter(!is.na(Metadata_vector)) %>%
  glimpse()
```

## regular plot

```{r}
plot_list <- plot_items %>% 
  map(\(x) pdata %>% 
        # filter(!is.na(cmpd)) %>% 
        ggplot(aes(barcode, !!as.name(x), 
                   fill=cmpd, 
                   color=cmpd)) +
        # stat_summary(geom="errorbar", fun.data=mean_sdl,
        #              fun.args=list(mult=1), # check Hmisc::smean.sdl
        #              width=0.4, color="grey20", # "#4575b4"
        #              position=position_dodge(0.75)) +
        stat_summary(geom="errorbar", fun.data=mean_se,
                    width=0.4, #color="grey20",
                     position=position_dodge(0.75)) +
        # stat_summary(geom="errorbar", fun.data=mean_se, width=0.1) + #color="grey20",
        stat_summary(geom="bar", fun=mean, width=0.5,
                     position=position_dodge(0.75)) +
        # stat_summary(geom="point", fun=mean, size=1.5) +
        # geom_smooth(se=T) +
        facet_wrap(vars(temperature), ncol=3,
                   scales="free_x", axes="all") +
        # facet_grid(rows=vars(cell, density),
        #            cols=vars(cmpd),
        #            scales="free_y", axes="all") +
        # ggpubr::stat_compare_means(
        #   aes(group=Metadata_temp, label=after_stat(p.format)),
        #   method="wilcox.test", size=1) +
        # guides(fill="none") +
        # scale_fill_hue(direction=-1) +
        # scale_fill_manual(values = colorRampPalette(brewer.pal(8, "Dark2"))(18)) +
        # scale_fill_manual(values=colorRampPalette(brewer.pal(9, "BuGn"))(11)) +
        # scale_log("x") +
        # labs(x="Dose (uM)") +
        theme_hh(axis_text_x_angle = 45) +
        theme(legend.position="top") +
        guides(fill=guide_legend(nrow=1), color=guide_legend(nrow=1))
  )
pdf(str_glue("{Sys.Date()}_{plot_obj}_plot.pdf"), width=15, height=3)
# print(plot_list[1])
for(i in plot_list) print(i)
while(dev.cur() != 1) dev.off()
```

## custom plot

```{r}
cpdata <- cell_tidy_per_well %>% 
  filter(!is.na(cmpd)) %>% 
  filter(str_detect(barcode, "Y220C")) %>%
  pivot_wider(id_cols = c(conc, temperature, timepoint, barcode),
              names_from = cell, 
              values_from = c(target_pred_prob_mean, target_pred_prob_se, 
                              target_pos_ratio_mean, target_pos_ratio_se,
                              intensity_mean_ch3_mean, intensity_mean_ch3_se)) %>% 
  print()
export(cpdata, str_glue("{Sys.Date()}_plot_correlation.xlsx"))

cpdata %>% 
  ggplot(aes(target_pred_prob_mean_Y220C, target_pred_prob_mean_mix)) +
  geom_smooth(linewidth = 0.75, color="#084594", fill="transparent", method="lm") +
  geom_point(aes(color=conc), size=2) +
  geom_errorbar(aes(xmin = target_pred_prob_mean_Y220C - target_pred_prob_se_Y220C,
                    xmax = target_pred_prob_mean_Y220C + target_pred_prob_se_Y220C,
                    color=conc),
                orientation="y", width = 0, linewidth = 0.5) +
  geom_errorbar(aes(ymin = target_pred_prob_mean_mix - target_pred_prob_se_mix,
                    ymax = target_pred_prob_mean_mix + target_pred_prob_se_mix,
                    color=conc),
                orientation="x", width = 0, linewidth = 0.5) +
  ggpubr::stat_cor(method="pearson", show.legend = F) +
  scale_color_manual(values = colorRampPalette(c("#BBD7FB", "#06346F"))(12)) +
  facet_wrap(vars(timepoint), scales="fixed", axes="all") +
  labs(x="Puncta probability (single Y220C well)", 
       y="Puncta probability (decoded from pooling)") +
  theme_hh()
ggsave(str_glue("{Sys.Date()}_plot_correlation.pdf"), width=9, height=3)


fitted <- cell_tidy_per_field %>% 
  filter(!is.na(cmpd)) %>%
  filter(timepoint == "37-2h") %>%
  filter(str_detect(barcode, "Y220C")) %>%
  fit_dose_response("conc", "target_pred_prob", group=c("cell", "timepoint", "barcode"))

sc150 <- fitted %>% 
  unnest(coef) %>%
  mutate(ICs=map(
    model, \(x) dr4pl::IC(x, inhib.percent=c(0.85)) %>% 
      enframe() %>% pivot_wider() )) %>% 
  unnest(ICs) %>% 
  dplyr::select(!c(data, model, pred)) %>% 
  dplyr::rename(sc150=`InhibPercent:0.85`) %>% 
  glimpse()

fitted_prepared <- plot_dose_response_dataPrepare(fitted, group="cell") %>% 
  left_join(sc150)
unnest(fitted_prepared, pred) %>% 
  dplyr::select(!c(data, model)) %>% 
  export(str_glue("{Sys.Date()}_plot_fit.xlsx"))

unnest(fitted, pred) %>% 
  ggplot(aes(x, y, color=cell)) +
  geom_line() + 
  stat_summary(aes(dose, response),
               geom="pointrange", 
               size=0.2, #color="#4575b4", 
               fun=mean, 
               fun.min = function(x) mean(x) - se(x), 
               fun.max = function(x) mean(x) + se(x),
               data=unnest(fitted_prepared, data), show.legend = F) +
  geom_text(aes(x, y, label=label),
    size=4, nudge_x=0.5, nudge_y=0.25,
    data=unnest(fitted_prepared, pred) %>%
      arrange(x, y) %>%
      slice_head(n=1, by=any_of("cell")) %>%
      mutate(label=str_c("SC150: ", format_num_auto(sc150))), show.legend = F) +
  # facet_wrap(vars(cell), scales="fixed", axes="all") +
  # facet_grid(rows=vars(barcode),
  #            cols=vars(timepoint),
  #            scales="fixed", axes="all") +
  scale_color_manual(values = c("mix"="#06346F", "Y220C"="#BC4F4F")) +
  scale_log("x") +
  labs(x="Dose (uM)", y="Puncta probability", caption="mean_se") +
  theme_hh(axis_text_x_angle = 0)
ggsave(str_glue("{Sys.Date()}_plot_fit.pdf"), width=4, height=3)
```

## heatmap

```{r}
metrics <- c(#"shape_equivalent_diameter_area_mean",
             # "intensity_mean_ch3_mean",
             "target_pred_prob_mean",
             "target_pos_ratio_mean"
)

cell_tidy_per_well %>%
  # filter(!is.na(cmpd)) %>% 
  filter(cmpd != "UA019") %>%
  # filter(temperature == "37") %>%# view()
  mutate(cmpd=droplevels(cmpd)) %>% 
  # filter(!barcode %in% c("WT", "R273H")) %>% #, "R248Q", "R175H"
  arrange(barcode) %>%
  dplyr::select(any_of(c("barcode", "cmpd", "temperature", metrics))) %T>% 
  export(str_glue("{Sys.Date()}_plot_heatmap.xlsx")) %>% 
  df2heatmap(metrics, row_by = "barcode", col_by = "cmpd",
             color=c("white"=0.2,"#06346F"=0.6), #scale_scope="split",
             border = "grey90",
             split_by = c("temperature"), 
             scale=NULL, row_cluster = F,
             x_text_angle=90) %>% 
  cowplot::plot_grid (plotlist = ., ncol=1)
ggsave(str_glue("{Sys.Date()}_plot_heatmap.pdf"), width=7, height=6)

# cell_tidy_per_well %>%
#   filter(is.na(cmpd)) %>% 
#   slice_max(cell_count_per_field_mean, n=1, by=c(cell, timepoint)) %>% 
#   # filter(cell != "mix") %>% 
#   # filter(timepoint == "37-2h") %>%# view()
#   # filter(!barcode %in% c("WT", "R248Q", "R273H", "R175H")) %>% 
#   arrange(timepoint) %>%
#   dplyr::select(any_of(c("cell", "timepoint", metrics))) %T>% 
#   export(str_glue("{Sys.Date()}_plot_heatmap_pure.xlsx")) %>% 
#   df2heatmap(metrics, row_by = "cell", col_by = "timepoint",
#              color=c("white"=0.15,"#06346F"=0.8), #scale_scope="split",
#              border = "grey90",
#              # split_by = c("timepoint"), 
#              scale=NULL, row_cluster = F,
#              x_text_angle=90) %>% 
#   cowplot::plot_grid (plotlist = ., ncol=1)
# ggsave(str_glue("{Sys.Date()}_plot_heatmap_pure.pdf"), width=7, height=4)
```

## reduction

```{r}
# single cell level pca
dr_plot <- cell_tidy %>% 
  dplyr::filter(temperature == "37") %>%
  # filter(!barcode %in% c("WT", "R248Q", "R273H", "R175H")) %>% 
  dplyr::slice_sample(n=100, by=any_of(meta_colnames)) %>% 
  ggplot(aes(pc_1_infer_p53, pc_2_infer_p53, 
             fill=barcode)) +
  ggrastr::geom_point_rast(size=2, stroke=0, alpha=0.7, shape=21, raster.dpi=300) +
  scale_fill_manual(values = colorRampPalette(brewer.pal(8, "Dark2"))(18)) +
  # facet_wrap(vars(temperature), ncol=4,
  #            scales="free_x", axes="all") +
  facet_grid(rows=vars(barcode),
             cols=vars(cmpd),
             scales="fixed", axes="all") +
  theme_hh(axis_text_x_angle = 0) +
  theme(legend.position="top")
ggsave(str_glue("{Sys.Date()}_dr_plot_37.pdf"), dr_plot, width=20, height=24)
```




# statistics analysis
## setting

```{r}
statistics_obj <- "cell"
# statistics_obj <- "cell_filter_field"

# normalized by group
statistics_grouping_vars <- c("Metadata_prefix") 

get_foldchange <- T # if calculate fold change to ctrl
log_trans <- F # if fc log2 transform
get_pvalue <- T # if calculate p-value
pvalue_items <- c("Intensity_MeanIntensity_ErkKTRActivity") # column names from statistics_obj

use_median <- T # if TRUE, ctrl_value will be set as median per group
ctrl_colname <- "Metadata_well" # uid for analysis
ctrl_value <- "0" # datatype must be same with column type, omit if use_median == T
ctrl_value <- ifelse(isTRUE(use_median), "median", ctrl_value)
```

## foldchange

```{r}
if(get_foldchange) {
  print(str_glue("use [{statistics_obj}] to calculate foldchange"))
  assign(
    str_glue("{statistics_obj}_stat"), 
    calculate_foldchange(
      get(statistics_obj), 
      ctrl_colname=ctrl_colname, ctrl_value=ctrl_value,
      grouping_vars=statistics_grouping_vars, use_median=use_median,
      log_trans=log_trans, mean_trim=0.05, const=0)
  )} else rm(list=str_subset(ls(), str_glue("^{statistics_obj}.*_stat$")))

if(get_pvalue) {
  print(str_glue("use [{statistics_obj}] to calculate pvalue"))
  assign(
    str_glue("{statistics_obj}_pval"), 
    calculate_pvalue(
      get(statistics_obj), 
      ctrl_colname=ctrl_colname, ctrl_value=ctrl_value,
      grouping_vars=statistics_grouping_vars, 
      pvalue_items=pvalue_items, use_median=use_median) )
  # merge pval with fc
  assign(
    str_glue("{statistics_obj}_stat"),
    left_join(get(str_glue("{statistics_obj}_stat")),
              get(str_glue("{statistics_obj}_pval"))) )
} else rm(list=str_subset(ls(), str_glue("^{statistics_obj}.*_pval$")))

# glimpse(get(str_glue("{statistics_obj}_stat")))
```


## pca distance
```{r}
pca_distance <- cell_tidy %>% 
  nest_by(across(any_of(setdiff(meta_colnames, c("well","cmpd"))))) %>% 
  mutate(data = calc_distance(
    dplyr::select(data, starts_with("pc_")), # select pca features
    group=data[["cmpd"]], 
    method="mmd", ref="DMSO") %>% 
      list() ) %>% 
  unnest(data)
pca_distance <- pca_distance %>% 
  dplyr::select(!group_1) %>% 
  dplyr::rename(cmpd=group_2)

```


# dose response

## fit setting

```{r}
# fitting_source: cell, cell_stat, cell_field, cell_field_stat
# glimpse(summary_per_field_normCtrl)
fitting_obj <- "cell_norm"
fitting_X <- "Metadata_conc"
fitting_Y <- "Granularity_2_GFP"
fitting_groupby <- c("Metadata_prefix","Metadata_cmpd")
# fitting_groupby <- NULL
```

## fit curve

```{r}
fitted <- get(fitting_obj) %>% 
  # filter(Metadata_cmpd=="Sema") %>% 
  fit_dose_response(
    fitting_X, fitting_Y, fitting_groupby, n_worker=1
    # # parameters from dr4pl::dr4pl()
    # trend = "decreasing",
    # method.init = "Mead",
    # method.robust = "Huber",
    # lowerl = c(theta_4 = 0)
    )
# prepare data to plot
# remove not converged group
fitted_prepared <- plot_dose_response_dataPrepare(
  fitted, group=fitting_groupby)
```

## plot fitted result

```{r}
p <- ggplot() +
  stat_summary(aes(dose, response),
               geom="pointrange", 
               color="#4575b4", size=0.2,
               fun=mean, 
               fun.min = function(x) mean(x) - se(x), 
               fun.max = function(x) mean(x) + se(x),
               data=unnest(fitted_prepared, data)) +
  geom_line(aes(x,y), color="#4575b4",
            data=unnest(fitted_prepared, pred)) + 
  geom_text(aes(x, y, label=label), 
    size=2, nudge_x=1, nudge_y=-0.25,
    data=unnest(fitted_prepared, pred) %>% 
      arrange(x, y) %>% 
      slice_head(n=1, by=any_of(fitting_groupby)) %>% 
      mutate(label=str_c("IC50: ", format_num_auto(IC50_Estimate),"\n",
                         "Upper: ", format_num_auto(as.numeric(Upper_Estimate)*100),"\n",
                         "Lower: ", format_num_auto(as.numeric(Lower_Estimate)*100)))) +
  facet_wrap(vars(Metadata_prefix),
             scales="fixed", axes="all") +
  # facet_grid(rows=vars(Metadata_prefix),
  #            cols=vars(Metadata_vector),
  #            scales="fixed", axes="all") +
  labs(x="Dose (uM)", y=fitting_Y, caption="mean_se") +
  scale_log("x") +
  # coord_cartesian(ylim=c(0, NA)) +
  theme_hh(axis_text_x_angle = 45)
# p
ggsave(str_glue("{Sys.Date()}_{fitting_obj}_DoseFit_{fitting_Y}.pdf"),
        p, width=12, height=3, limitsize=F)
```

## save fitted data

```{r}
fitted_save_data <- fitted %>% 
  unnest(coef) %>%
  # add more IC values
  mutate(ICs=map(
    model, 
    \(x) dr4pl::IC(x, inhib.percent=c(10, 50, 90)) %>% 
      enframe() %>% 
      pivot_wider() )) %>% 
  unnest(ICs) %>% 
  select(!c(data, model, pred))

writexl::write_xlsx(
  list(fitted=fitted_save_data), 
  str_glue("{Sys.Date()}_{fitting_obj}_DoseFit_{fitting_Y}.xlsx"))
```

