---
title: "plate reader data analysis"
format: html
editor_options: 
  chunk_output_type: console
---

#---------------------------------
# prepare data

```{r}
rstudioapi::getActiveDocumentContext()$path |>
  dirname() |>
  setwd()

# options("repos" = c(CRAN="https://mirrors.ustc.edu.cn/CRAN/")) 
# options(BioC_mirror="https://mirrors.ustc.edu.cn/bioc/")
options("repos" = c(CRAN="https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
options(BioC_mirror="https://mirrors.tuna.tsinghua.edu.cn/bioconductor")

# load packages
library(tidyverse)
library(rio)
library(patchwork)
library(RSQLite)
library(RColorBrewer)
options(rio.import.class='tbl')

# load helper function
c("helper.R", 
  "fit_ic50.R",
  "ggplot_helper.R") %>% 
  # file.path("F:\\GitHub\\myScript\\R", .) %>%
  walk(source)

# set wd
r"(F:\workspace\artes)" %>% 
  norm_path() %>% 
  setwd()
```


## read plate data
```{r}
raw <- list.files("./2026-07-02_CTG_96h", ".csv", full.names = T) %>%
  set_names(., nm = \(x) str_extract(x, "[^/\\\\]+(?=\\.csv)")) %>%
  map(\(x) read_csv(x, skip=5)) %>%
  list_rbind(names_to = "plate") %>%
  janitor::clean_names() %>%
  transmute(
    plate = plate,
    well = transform_well_style(well_id),
    value = result_channel_1) %>%
  glimpse()
```


## merge metadata
```{r}
plate_info_files <- list.files(
    ".", "plate_info.xlsx",
    recursive = T, full.names = T) %>%
    set_names(., nm = \(x) str_extract(x, "[^/\\\\]+(?=\\.xlsx)")) %>%
    print()

if (length(plate_info_files) > 0) {
  plate_info <- plate_info_files %>%
    map(read_metadata) %>%
    {
      if(length(plate_info_files) > 1) list_rbind(., names_to='plate') else list_rbind(.)
    } %>% 
    # rename(Metadata_vector=value) %>%
    # separate_wider_delim(value, delim=regex("[+ ]"),
    #                      names=c("Metadata_vector", "Metadata_type", "Metadata_adaptor"),
    #                      too_few="align_start",
    #                      cols_remove=T) %>%
    # mutate(Metadata_vector=factor(Metadata_vector, c("Gal4DBD","APP","NOTCH1"))) %>%
    # mutate(RSL3_conc = as.numeric(RSL3_conc)) %>%
    print()
}

# merge with plate_info
if (exists("plate_info")) {
  data <- raw %>%
    left_join(plate_info, .) %>%
    # right_join(plate_info, .) %>%
    # filter() %>%
    glimpse()
}
```



# ---------------------------------
# plot

## pdata
```{r}
pdata <- data %>%
  mutate(value=round(as.numeric(value), 0)) %>%
  mutate(conc=round(as.numeric(conc), 4)) %>%
  separate_wider_regex(plate, c("CTG_96h_", cell=".*"), cols_remove=T) %>% 
  mutate(cell=factor(cell, c("H1299", "TPC1", "FPC133"))) %>% 
  ## norm by day0
  # mutate(across(!value,
  #               \(x) round(x / mean(x[date == "06-28"], na.rm=T), 3)),
  #        .keep="used",
  #        .by=c(cell, cmpd, density, conc)) %>%
  ## norm by DMSO
  mutate(value_norm = round(value / mean(value[cmpd == "DMSO"], na.rm=T), 3),
         .keep="used",
         .by=c(cell, density, conc)) %>%
  ## norm by lowest conc
  # mutate(cmpd=cmpd,
  #        value_norm = round(value / mean(value[conc == min(.data[["conc"]])]), 3),
  #        .keep="used",
  #        .by=c(cell, density)) %>%
  filter(!(cmpd %in% c("DMSO"))) %>% 
  glimpse()

# set x conc range
xrng <- range(pdata$conc[pdata$conc > 0], na.rm=T) %>% print()
```

## save
```{r}
pdata %>% 
  export(str_glue("{Sys.Date()}_CTG.xlsx"))
```

## plot
```{r}
# select last point of each line
label_df <- pdata %>%
  slice_max(conc, n=1, by=c(cell, density, cmpd)) %>% 
  print()

pdf(str_glue("{Sys.Date()}_CTG.pdf"), width=9, height=9)

pdata %>% 
  ggplot(aes(conc, value_norm, fill=cmpd, color=cmpd)) +
  # stat_summary(geom="errorbar", fun.data=mean_sdl,
  #              fun.args=list(mult=1), # check Hmisc::smean.sdl
  #              width=0.4, color="grey20", # "#4575b4"
  #              position=position_dodge(0.75)) +
  # stat_summary(geom="bar", fun=mean, color="grey50", linewidth=0.25,
  #              width=0.7, #fill="#4575b4",
  #              position=position_dodge(0.75)) + 
  stat_summary(geom="errorbar", fun.data=mean_se, width=0.1) + #color="grey20",
  stat_summary(geom="line", fun=mean, linewidth=0.5) + 
  stat_summary(geom="point", fun=mean, size=1.5) + 
  # geom_smooth(se=T) +
  facet_wrap(vars(cell, density), ncol=2,
             scales="free_x", axes="all") +
  # facet_grid(rows=vars(cell, density),
  #            cols=vars(cmpd),
  #            scales="free_y", axes="all") +
  # ggpubr::stat_compare_means(
  #   aes(group=Metadata_temp, label=after_stat(p.format)),
  #   method="wilcox.test", size=1) +
  # guides(fill="none") +
  # scale_fill_hue(direction=-1) +
  # scale_fill_brewer("BuGn") +
  # scale_color_manual(values=colorRampPalette(brewer.pal(9, "Set1"))(15)) +
  scale_x_log10(#limits=c(xrng[1], 10^ceiling(log10(xrng[2]))),
                breaks=10^(floor(log10(xrng[1])):ceiling(log10(xrng[2]))),
                labels=\(x) scales::label_math(10^.x)(log10(x))) +
  # label lines
  ggrepel::geom_text_repel(
    aes(label=cmpd, color=cmpd), size=2, data=label_df, 
    direction="y", hjust=0, nudge_x=0.5,
    segment.size=0.25, #segment.color="grey50", 
    box.padding=0.3, point.padding=0.2,
    force=2, max.overlaps=20, show.legend=F) +
  labs(x="Concentration (uM)") +
  my_theme(angle=0) +
  theme(legend.position="top")

while(dev.cur() != 1) dev.off()
```



# --------------------------------------------------
# dose response

## fit setting
```{r}
# fitting_source: cell, cell_stat, cell_field, cell_field_stat
# glimpse(summary_per_field_normCtrl)
fitting_obj <- "pdata"
fitting_X <- "conc"
fitting_Y <- "CTG_norm"
fitting_groupby <- c("cell", "density", "cmpd")
# fitting_groupby <- NULL
```

## fit curve
```{r}
fitted <- get(fitting_obj) %>% 
  # filter(Metadata_cmpd=="Sema") %>% 
  fit_dose_response(
    fitting_X, fitting_Y, fitting_groupby, n_worker=8
    # # parameters from dr4pl::dr4pl()
    # trend = "decreasing",
    # method.init = "Mead",
    # method.robust = "Huber",
    # lowerl = c(theta_4 = 0)
    )
# prepare data to plot
# remove not converged group
fitted_prepared <- plot_dose_response_dataPrepare(
  fitted, group=fitting_groupby)
```

## plot fitted result
```{r}
conc_series <- unique(pull(unnest(fitted_prepared, data), dose))
log_trans_sigma <- conc_series %>% setdiff(0) %>% min() %>% 
  magrittr::divide_by(10)

axis_breaks <- conc_series %>% setdiff(0) %>% range() %>% 
  log10() %>% round() %>% {seq(.[1], .[2], by=1)} %>% {10^(.)}

if(0 %in% conc_series) axis_breaks <- c(0, axis_breaks)

label_df_ds <- unnest(fitted_prepared, pred) %>% 
  group_by(cell, density, cmpd) %>% 
  mutate(x_diff=x-median(as.numeric(IC50_Estimate))) %>% 
  slice_min(abs(x_diff), n=1, with_ties=F) %>% 
  dplyr::select(x, y) %>% 
  ungroup() %>% 
  print()


p <- ggplot() +
  # stat_summary(aes(dose, response, color=cmpd),
  #              geom="pointrange", size=0.2, fun=mean,
  #              fun.min = function(x) mean(x) - se(x),
  #              fun.max = function(x) mean(x) + se(x),
  #              # color="#4575b4",
  #              data=unnest(fitted_prepared, data)) +
  geom_line(aes(x, y, color=cmpd), #color="#4575b4",
            data=unnest(fitted_prepared, pred), show.legend=F) +
  # geom_text(aes(x, y, label=label), 
  #   size=2, nudge_x=1, nudge_y=-0.25,
  #   data=unnest(fitted_prepared, pred) %>% 
  #     arrange(x, y) %>% 
  #     slice_head(n=1, by=any_of(fitting_groupby)) %>% 
  #     mutate(label=str_c("IC50: ", format_num_auto(IC50_Estimate),"\n",
  #                        "Upper: ", format_num_auto(as.numeric(Upper_Estimate)*100),"\n",
  #                        "Lower: ", format_num_auto(as.numeric(Lower_Estimate)*100)))) +
  facet_wrap(vars(cell, density), ncol=2,
             scales="fixed", axes="all") +
  # facet_grid(rows=vars(Metadata_prefix),
  #            cols=vars(Metadata_vector),
  #            scales="fixed", axes="all") +
  labs(x="Dose (uM)", y=fitting_Y, caption="mean_se") +
  # scale_x_continuous(
  #   transform=scales::pseudo_log_trans(sigma=log_trans_sigma, base=10),
  #   breaks=axis_breaks,
  #   # labels=scales::label_number(drop0trailing=T),
  #   expand=expansion(mult=c(0.05, 0.1)),
  #   labels=function(lab) {
  #     do.call(expression, lapply(paste(lab), function(x) bquote(.(x))))
  #   } ) +
  scale_x_log10(#limits=c(xrng[1], 10^ceiling(log10(xrng[2]))),
    breaks=10^(floor(log10(xrng[1])):ceiling(log10(xrng[2]))),
    labels=\(x) scales::label_math(10^.x)(log10(x))) +
  # label lines
  ggrepel::geom_label_repel(
    aes(x, y, label=cmpd, color=cmpd), size=2, data=label_df_ds, 
    direction="y", hjust=0, nudge_x=0.5,
    segment.size=0.25, #segment.color="grey50", 
    box.padding=0.3, point.padding=0.2,
    force=2, max.overlaps=20, show.legend=F) +
  my_theme(angle=0)
# p
ggsave(str_glue("{Sys.Date()}_CTG_DoseFit_{fitting_Y}.pdf"),
        p, width=12, height=12, limitsize=F)
```

## save fitted data
```{r}
fitted_save_data <- fitted %>% 
  unnest(coef) %>%
  # add more IC values
  mutate(ICs=map(
    model, 
    \(x) dr4pl::IC(x, inhib.percent=c(10, 50, 90)) %>% 
      enframe() %>% 
      pivot_wider() )) %>% 
  unnest(ICs) %>% 
  select(!c(data, model, pred))

writexl::write_xlsx(
  list(fitted=fitted_save_data), 
  str_glue("{Sys.Date()}_CTG_DoseFit_{fitting_Y}.xlsx"))
```

